-- RentArena: схема базы данных для Supabase
-- Запустить один раз: Supabase Dashboard → SQL Editor → New query → вставить весь файл → Run

-- ============================================================
-- Профили пользователей (клиент или админ стадиона)
-- ============================================================
create table if not exists public.profiles (
	id uuid primary key references auth.users (id) on delete cascade,
	full_name text not null default '',
	phone text not null default '',
	role text not null default 'client' check (role in ('client', 'admin')),
	created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles: read own" on public.profiles;
create policy "profiles: read own" on public.profiles
	for select using (auth.uid() = id);

drop policy if exists "profiles: update own" on public.profiles;
create policy "profiles: update own" on public.profiles
	for update using (auth.uid() = id)
	with check (auth.uid() = id);

-- Профиль создаётся автоматически при регистрации (данные из формы регистрации)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
	insert into public.profiles (id, full_name, phone, role)
	values (
		new.id,
		coalesce(new.raw_user_meta_data ->> 'full_name', ''),
		coalesce(new.raw_user_meta_data ->> 'phone', ''),
		case when new.raw_user_meta_data ->> 'role' = 'admin' then 'admin' else 'client' end
	);
	return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
	after insert on auth.users
	for each row execute function public.handle_new_user();

-- Роль нельзя поменять самому себе через API
create or replace function public.prevent_role_change()
returns trigger
language plpgsql
as $$
begin
	if new.role <> old.role and auth.role() <> 'service_role' then
		raise exception 'role cannot be changed';
	end if;
	return new;
end;
$$;

drop trigger if exists profiles_prevent_role_change on public.profiles;
create trigger profiles_prevent_role_change
	before update on public.profiles
	for each row execute function public.prevent_role_change();

-- ============================================================
-- Стадионы
-- ============================================================
create table if not exists public.arenas (
	id bigint generated by default as identity primary key,
	owner_id uuid references public.profiles (id) on delete set null,
	name text not null,
	category text not null default 'stadion' check (category in ('stadion', 'footzal')),
	location text not null default '',
	admin_phone text not null default '',
	price_per_hour integer not null default 0 check (price_per_hour >= 0),
	open_hour smallint not null default 8 check (open_hour between 0 and 23),
	close_hour smallint not null default 24 check (close_hour between 1 and 24),
	coverage text not null default '',
	payment_info text not null default '',
	features text[] not null default '{}',
	images text[] not null default '{}',
	is_published boolean not null default true,
	created_at timestamptz not null default now(),
	check (close_hour > open_hour)
);

alter table public.arenas enable row level security;

drop policy if exists "arenas: public read" on public.arenas;
create policy "arenas: public read" on public.arenas
	for select using (is_published or owner_id = auth.uid());

drop policy if exists "arenas: admin insert" on public.arenas;
create policy "arenas: admin insert" on public.arenas
	for insert with check (
		owner_id = auth.uid()
		and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
	);

drop policy if exists "arenas: owner update" on public.arenas;
create policy "arenas: owner update" on public.arenas
	for update using (owner_id = auth.uid())
	with check (owner_id = auth.uid());

drop policy if exists "arenas: owner delete" on public.arenas;
create policy "arenas: owner delete" on public.arenas
	for delete using (owner_id = auth.uid());

-- ============================================================
-- Брони: одна строка = один час на одном поле
-- ============================================================
create table if not exists public.bookings (
	id bigint generated by default as identity primary key,
	arena_id bigint not null references public.arenas (id) on delete cascade,
	user_id uuid references public.profiles (id) on delete set null,
	date date not null,
	hour smallint not null check (hour between 0 and 23),
	customer_name text not null default '',
	customer_phone text not null default '',
	status text not null default 'confirmed' check (status in ('confirmed', 'cancelled')),
	source text not null default 'online' check (source in ('online', 'manual')),
	created_at timestamptz not null default now()
);

-- Главная защита: один и тот же час нельзя забронировать дважды
create unique index if not exists bookings_no_double_booking
	on public.bookings (arena_id, date, hour)
	where status = 'confirmed';

create index if not exists bookings_user_idx on public.bookings (user_id);

alter table public.bookings enable row level security;

-- Клиент видит свои брони, админ — все брони своих стадионов
drop policy if exists "bookings: read own or owner" on public.bookings;
create policy "bookings: read own or owner" on public.bookings
	for select using (
		user_id = auth.uid()
		or exists (select 1 from public.arenas a where a.id = arena_id and a.owner_id = auth.uid())
	);

-- Клиент бронирует онлайн для себя, админ добавляет брони вручную (звонок, WhatsApp и т.д.)
drop policy if exists "bookings: insert" on public.bookings;
create policy "bookings: insert" on public.bookings
	for insert with check (
		status = 'confirmed'
		and (
			(source = 'online' and user_id = auth.uid())
			or (
				source = 'manual'
				and exists (select 1 from public.arenas a where a.id = arena_id and a.owner_id = auth.uid())
			)
		)
	);

-- Проверка: час в пределах режима работы и онлайн-бронь не в прошлом (время Душанбе)
create or replace function public.validate_booking()
returns trigger
language plpgsql
as $$
declare
	a public.arenas;
begin
	select * into a from public.arenas where id = new.arena_id;
	if new.hour < a.open_hour or new.hour >= a.close_hour then
		raise exception 'hour outside working hours';
	end if;
	if new.source = 'online'
		and (new.date + make_time(new.hour, 0, 0)) < (now() at time zone 'Asia/Dushanbe') then
		raise exception 'cannot book in the past';
	end if;
	return new;
end;
$$;

drop trigger if exists bookings_validate on public.bookings;
create trigger bookings_validate
	before insert on public.bookings
	for each row execute function public.validate_booking();

-- Занятые часы поля на дату — доступно всем, без личных данных клиентов
create or replace function public.get_busy_hours(p_arena_id bigint, p_date date)
returns setof smallint
language sql
stable
security definer set search_path = public
as $$
	select hour from public.bookings
	where arena_id = p_arena_id and date = p_date and status = 'confirmed'
	order by hour;
$$;

grant execute on function public.get_busy_hours(bigint, date) to anon, authenticated;

-- Отмена брони: клиент — свою будущую, админ — любую на своём поле
create or replace function public.cancel_booking(p_booking_id bigint)
returns void
language plpgsql
security definer set search_path = public
as $$
declare
	b public.bookings;
begin
	select * into b from public.bookings where id = p_booking_id;
	if not found then
		raise exception 'booking not found';
	end if;

	if exists (select 1 from public.arenas a where a.id = b.arena_id and a.owner_id = auth.uid()) then
		null;
	elsif b.user_id = auth.uid() then
		if (b.date + make_time(b.hour, 0, 0)) < (now() at time zone 'Asia/Dushanbe') then
			raise exception 'cannot cancel past booking';
		end if;
	else
		raise exception 'not allowed';
	end if;

	update public.bookings set status = 'cancelled' where id = p_booking_id;
end;
$$;

grant execute on function public.cancel_booking(bigint) to authenticated;

-- Админка обновляется в реальном времени, когда кто-то бронирует
do $$
begin
	if not exists (
		select 1 from pg_publication_tables
		where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'bookings'
	) then
		alter publication supabase_realtime add table public.bookings;
	end if;
end;
$$;

-- ============================================================
-- Хранилище фото стадионов
-- ============================================================
insert into storage.buckets (id, name, public)
values ('arena-images', 'arena-images', true)
on conflict (id) do nothing;

drop policy if exists "arena-images: public read" on storage.objects;
create policy "arena-images: public read" on storage.objects
	for select using (bucket_id = 'arena-images');

-- Админ загружает фото только в свою папку: arena-images/<user_id>/...
drop policy if exists "arena-images: owner upload" on storage.objects;
create policy "arena-images: owner upload" on storage.objects
	for insert to authenticated with check (
		bucket_id = 'arena-images'
		and (storage.foldername(name))[1] = auth.uid()::text
	);

drop policy if exists "arena-images: owner delete" on storage.objects;
create policy "arena-images: owner delete" on storage.objects
	for delete to authenticated using (
		bucket_id = 'arena-images'
		and (storage.foldername(name))[1] = auth.uid()::text
	);

-- ============================================================
-- Права доступа к таблицам (что именно можно — решают политики RLS выше)
-- ============================================================
grant usage on schema public to anon, authenticated;
grant select on public.arenas to anon, authenticated;
grant insert, update, delete on public.arenas to authenticated;
grant select, update on public.profiles to authenticated;
grant select, insert on public.bookings to authenticated;
grant usage, select on all sequences in schema public to authenticated;
