-- Демо-данные: стадионы, которые раньше были на mokky.dev
-- Запустить после schema.sql (SQL Editor → Run)

insert into public.arenas (name, category, location, admin_phone, price_per_hour, open_hour, close_hour, coverage, payment_info, features, images)
values
	('Футбольное поле ''Душанбе Арена''', 'stadion', 'г. Душанбе, ул. У. Хайём 102 (ориентир: Аграрный унив., Сельхоз)', '90 738 54 25', 0, 0, 24, 'искусственное покрытие', 'лично админу по приезду', array['Искусственное покрытие', 'Освещение', 'Раздевалки']::text[], array['/assets/dushanbe-arena.jpg']::text[]),
	('Футбольный манеж ''Мачмаи варзиши''', 'footzal', 'г. Душанбе, ул. А.Фирдавси (ориентир: Технологический унив.)', '98 543 05 07', 0, 0, 24, 'твёрдая резина', 'лично админу по приезду', array['Освещение', 'Раздевалки', 'Душ', 'Парковка']::text[], array['https://sportzone.tj/uploads/images/2021-09-23/yHBD3vh7x2Xcvh36yCGiQaxg4jCBdPG5qrfRXqQO.jpg', 'https://sportzone.tj/uploads/images/2021-09-23/8o729UsIQRPUz8NzUmVpYJITIAFXrIUwLuqTgFeh.jpg', 'https://sportzone.tj/uploads/images/2021-09-23/1DZDxsinb3wddguLRfZUlPojvN8CrW7RNPHewew4.jpg']::text[]),
	('Футбольное поле ''Спорткомплекс''', 'stadion', 'г. Душанбе, ул. У. Хайём 102 (ориентир: Аграрный унив., Сельхоз)', '90 738 54 25', 0, 0, 24, 'искусственное покрытие', 'лично админу по приезду', array['Искусственное покрытие', 'Освещение', 'Раздевалки']::text[], array['https://sportzone.tj/uploads/images/2021-09-15/FiWAjvXNmCIrBjZDFbVpxhvLUTxHfulU0SyxS4iD.jpg']::text[]),
	('Мини футбольное поле', 'stadion', 'профсоюз', '90 738 54 25', 0, 17, 22, 'искусственное покрытие', 'лично админу по приезду', array['Искусственное покрытие', 'Освещение', 'Инвентарь']::text[], array['https://sportzone.tj/uploads/images/2021-09-23/eL46iXyA6JKWQFj9uKiMECcBgFiBNxjl1kz1FJey.jpg', 'https://sportzone.tj/uploads/images/2021-09-23/XaCDlrxrkeoqD08EHJ6Os6Pcm35OE8O3AasbiPaW.jpg', 'https://sportzone.tj/uploads/images/2021-09-23/Od2coUW2qZZpbKXUCoM5e90Er62edJCEFTu6hnJx.jpg']::text[]),
	('Футбольный манеж в фитнес-клубе ''X-Fit''', 'footzal', 'Ул. Колхозная', '7772', 0, 8, 22, 'искусственное покрытие', 'лично админу по приезду', array['Искусственное покрытие', 'Освещение', 'Инвентарь', 'раздевалка', 'душ', 'парковка']::text[], array['https://sportzone.tj/uploads/images/2021-09-23/7PzwsFOOqvjM4n4sIsmX6bWH9a8kTsRegV9vRYLm.jpg', 'https://sportzone.tj/uploads/images/2021-09-23/tj5K7N3U3xmXlaRMKcdvcIkr0sY71ZAnTBioE6K8.jpg', 'https://sportzone.tj/uploads/images/2021-09-23/KJmCFTcd9GiIKJDc9aj9l3eKfbzPVpINJdjDK4lt.jpg']::text[]);
